# 应用服务 WEB 访问端口
server:
  port: 7090
  servlet:
    context-path: /api
    # session过期时间 60M 一个小时
    session:
      timeout: PT60M

# 异常处理
spring:
  mvc:
    # 处理favicon
    favicon:
      enable: false
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # 数据库配置
  datasource:
    url: jdbc:mysql://gottenzzp.top:3306/mynetdisk?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: macuser
    password: 199807
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # 发送邮件配置相关
  mail:
    # 配置邮件服务器的地址 smtp.qq.com
    host: smtp.qq.com
    # 配置邮件服务器的端口（465或587）
    port: 465
    # 配置用户的账号
    username: 1319830200@qq.com
    # 配置用户的密码
    password: eccrgzuddpwajgjf
    # 配置默认编码
    default-encoding: UTF-8
    # SSL 连接配置
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        # 开启 debug，这样方便开发者查看邮件发送日志
        debug: true
  # Spring redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: gottenzzp.top
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 2000

# 项目目录
project:
  folder: /Users/gottenzzp/Documents/java_code/MyNetDisk/

# 日志级别配置
log:
  root:
    level: info

# 超级管理员id
admin:
  emails: test@qq.com

# 是否是开发环境
dev: false

# qq登陆相关
qq:
  app:
    id: 12333
    key: 2222222
  url:
    authorization: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    access:
      token: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    openid: https://graph.qq.com/oauth2.0/me?access_token=%S
    user:
      info: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
    redirect: http://easypan.wuhancoder.com/qqlogincalback
